### ISSUE TITLE
Clarify what OTP means

### ISSUE THREAD

**Issue by hardliner66** [dnaka91/otti#1]
It took me a while that you don't mean [Erlang/OTP](http://erlang.org/doc/). Would be nice if the README would spell out OTP at least once, to avoid confusion.

**Comment by dnaka91** [comment]
Hey there @hardliner66 thanks for letting me know. I wasn't aware that there are other popular meanings for OTP.

I'll spell it out in the readme and descriptions tomorrow.

**Comment by dnaka91** [comment]
I updated the readme with an extra section about OTP and wrote it out in the first line.

Please have a look and close the issue if you think it'll suffice 🙇‍♂️

**Comment by hardliner66** [comment]
Perfect, thanks.
