### ISSUE TITLE
Out-dated version of cargo causing error

### ISSUE THREAD

**Issue by Quix0r** [dnaka91/otti#5]
I get the following error message:
````
error: failed to parse manifest at `/home/xxx/git/otti/Cargo.toml`

Caused by:
  invalid type: map, expected a sequence for key `package.authors`
````
`cargo` has version: 1.46.0

Maybe you can put a condition (I don't know rust/cargo enough) in that checks minimum version before proceeding?

Someone with 1.67.1 was able to build otti:
https://masto.pt/@brunomiguel/109847817419577424

**Comment by dnaka91** [comment]
Hey there, cargo 1.46.0 is pretty dated. You'll need at least **1.64** to be able to compile this project. I'd personally recommend using `rustup` to manage Rust toolchains.

I guess you're maybe on Ubuntu or Debian and use the package manager's version of cargo? As they're usually very outdated.

The alternative would be to download the pre-compiled version from the [release page](https://github.com/dnaka91/otti/releases/tag/v0.2.7), in the hopes that one of them matches your platform target.

**Comment by Quix0r** [comment]
I have here another package `cargo-mozilla`. It is declared as a Rust package manager (like `compose` from PHP, `mvn` for Java, `pip` for Python?). I try this one.

**Comment by Quix0r** [comment]
It reports now `cargo 1.56.0`. Looks like this is the minimum version I need. But I still get the same error back.

**Comment by dnaka91** [comment]
Sorry, as I said you'll need `cargo 1.64.0` at least, or it won't compile. Therefore, `cargo 1.56.0` won't work either.

Also, I likely use features that increase the minimum required Rust version even more in the future. So I can't give any promise that it will compile with 1.64 that long. Usually I always use the latest version of Rust.

So best would really be if you use [`rustup`](https://www.rust-lang.org/learn/get-started) instead, which is the recommended way of installing and managing Rust toolchains. Then all you have to do is call `rustup install stable` to get the latest version.

Or use the pre-compiled binaries, as mentioned before. But I can understand that people might prefer to compile it themselves, over some random binary from the Internet :sweat_smile:.

**Comment by Quix0r** [comment]
Oh, okay. Then I wasn't not realizing it. ;-)
